# Generated by Django 3.2.3 on 2021-06-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProducto', '0004_auto_20210611_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_genero',
            new_name='nombre_categoria',
        ),
    ]
