# Generated by Django 3.2.3 on 2021-06-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProducto', '0005_rename_nombre_genero_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nombre_marca',
            new_name='nombre',
        ),
    ]
